server:
  port: 8084
spring:
  datasource:
    url: ${JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PSW}
    driver-class-name: ${JDBC_DRIVER}
    test-on-borrow: false
    test-while-idle: false
    validation-query: select 1;
    maxActive: 1
  jpa:
    properties:
      show-sql: false
      generate-ddl: true
    hibernate:
      dialect: org.hibernate.dialect.MariaDB53Dialect
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 465
    username: felipexalves@gmail.com
    password: Fa16171608!
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        ssl:
          enable: true
    test-connection: false
    
      
